//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dcuFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class asignacion
    {
        [DisplayName("ID Asignacion")]
        public int ID { get; set; }
        [DisplayName("ID Materia")]
        public Nullable<int> Materia_ID { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        [DisplayName("Fecha")]
        public System.DateTime fecha { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Gradp")]
        public string grado { get; set; }
        [DisplayName("Año")]
        public Nullable<int> año { get; set; }
        [DisplayName("Competencia")]
        public string competencia { get; set; }
        [DisplayName("Estrategia")]
        public string estrategia { get; set; }
        [DisplayName("Recursos")]
        public string recursos { get; set; }
        [DisplayName("Evaluacion")]
        public int evaluacion { get; set; }
    
        public virtual Materia Materia { get; set; }
    }
}
